print("Hello and welcome to the Band Name Generator")
print("Whats is the name of the city you grew up in?")
cityname = input()
print("What is the name of your pet?")
petname = input()
print("Your new Band Name is")
print(cityname + " " + petname)